# Generated by Django 3.1.2 on 2020-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxForeclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named_defendant', models.CharField(max_length=128)),
                ('case_number', models.CharField(max_length=12)),
                ('parcels', models.ManyToManyField(to='parcels.Parcel')),
            ],
        ),
    ]
