# Generated by Django 3.1.2 on 2020-11-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_half', models.DecimalField(decimal_places=2, max_digits=12)),
                ('second_half', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.taxtype')),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.taxyear')),
            ],
        ),
    ]
